version: "3.4"
services:
  all:
    build: .
    expose:
      - "3306"
      - "8081"
      - "80"
    ports:
      - "8081:8081"
      - "3306:3306"
      - "80:80"
    volumes:
      - "./docker-volumes/mariadb:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "racp"
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "racp"
      MYSQL_PASSWORD: "racp"
      MYSQL_DATABASE: "racp"
      MYSQL_PORT: 3306
      MYSQL_HOST: "localhost"
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "admin"
      port: 8081
      hostname: 0.0.0.0
      jwtSecret: "secret"
      apiBaseUrl: "http://localhost:8081"
      adminPermissionName: "channel_admin"
