name: CI
on: ["push"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn test

  #  e2e-test-docker:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v3
  #      - run: docker-compose pull
  #      - uses: satackey/action-docker-layer-caching@v0.0.11
  #        continue-on-error: true
  #      - run: docker-compose up --build --exit-code-from cypress
  #        env:
  #          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
  #          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  e2e-test-ci:
    runs-on: ubuntu-latest
    container: cypress/included:9.7.0
    steps:
      - uses: actions/checkout@v3

      - name: Restore yarn workspaces
        id: yarn-cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --no-progress --non-interactive

      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          mysql root password: racp
          mysql database: ragnarok
          mysql user: ragnarok
          mysql password: ragnarok

      - run: yarn e2e:ci:run
        env:
          MYSQL_PORT: 3306
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: ragnarok
          MYSQL_PASSWORD: ragnarok
          MYSQL_DATABASE: ragnarok
          NODE_ENV: production
          apiPort: 8081
          appPort: 8080
          apiBaseUrl: http://localhost:8081
          rAthenaPath: "${{ env.GITHUB_WORKSPACE }}/node_modules/rathena"
          CYPRESS_BASE_URL: http://localhost:8080
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
