name: CI
on: ["push"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn lint
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn test
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "ksandin"
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: "ghcr.io"
          image_name: "racp/${{ github.ref_name }}"
          compose_file: docker-compose.yml
      - run: >
          CYPRESS_PROJECT_ID=${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}
          docker-compose up --build --exit-code-from cypress
