name: Deploy
on: ["push"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script_stop: true
          script: |
            killall node || echo "No node process available to kill"
            mkdir -p /opt/
            git clone https://github.com/${{ github.repository }}.git /opt/racp/
            cd /opt/racp/
            git checkout ${{github.sha}}
            yarn install

            export NODE_ENV=production
            export apiPort=8081
            export appPort=80
            export apiBaseUrl=http://${{ secrets.DEPLOY_HOST }}:8081
            export rAthenaPath=./node_modules/rathena
            export log=verbose

            yarn api:prod & yarn app:prod &
