name: Deploy
on: ["push"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - run: yarn install --frozen-lockfile

      - name: "Build"
        env:
          NODE_ENV: production
          hostname: 0.0.0.0
          apiPort: ${{ secrets.DEPLOY_API_PORT }}
          appPort: ${{ secrets.DEPLOY_APP_PORT }}
          apiBaseUrl: //${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_API_PORT }}
          rAthenaPath: ./node_modules/rathena
          log: verbose
        run: yarn build

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          source: "dist"
          target: "/opt/racp"
          rm: true
