name: Deploy
on: ["push"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script_stop: true
          script: |
            killall node || echo "No node process available to kill"
            if cd /opt/racp/;
              then 
                git pull origin ${{github.sha}};
              else 
                git clone https://github.com/${{ github.repository }}.git /opt/racp/; 
            fi
            cd /opt/racp/
            git checkout ${{github.sha}}
            yarn install

            export NODE_ENV=production
            export hostname=0.0.0.0
            export apiPort=${{ secrets.DEPLOY_API_PORT }}
            export appPort=${{ secrets.DEPLOY_APP_PORT }}
            export apiBaseUrl=//${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_API_PORT }}
            export rAthenaPath=./node_modules/rathena
            export log=verbose

            yarn api:prod & yarn app:prod & disown
