name: Deploy
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".github/workflows/tests.yml"
      - ".github/workflows/e2e.reusable.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ env.DEPLOY_ENABLED }} == true
    env:
      DEPLOY_ENABLED: ${{ secrets.DEPLOY_ENABLED }}
      DEPLOY_PATH: /opt/racp
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Build
        env:
          apiBaseUrl: //${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_API_PORT }}
        run: |
          yarn install --frozen-lockfile
          NODE_ENV=production && yarn app:build

      - name: Upload
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --exclude="node_modules"
          remote_path: ${{ env.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USERNAME }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: (Re)start services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}

            # Make sure dependencies are installed
            yarn install

            # Set API env vars
            export hostname=${{ secrets.DEPLOY_HOST }}
            export apiPort=${{ secrets.DEPLOY_API_PORT }}
            export appPort=${{ secrets.DEPLOY_APP_PORT }}
            export rAthenaPath=${{ secrets.DEPLOY_RATHENA_PATH }}
            export log=verbose

            pm2 restart ecosystem.config.json
