name: Deploy
on: ["push"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script_stop: true
          script: |
            racpFolder=/opt/racp/

            if [ ! -d $racpFolder ]
              then
                git clone https://github.com/${{ github.repository }}.git $racpFolder
                cd $racpFolder
                git checkout ${{github.sha}}
              else
                cd $racpFolder
                git pull origin ${{github.sha}}
            fi

            yarn install

            export NODE_ENV=production
            export hostname=0.0.0.0
            export apiPort=${{ secrets.DEPLOY_API_PORT }}
            export appPort=${{ secrets.DEPLOY_APP_PORT }}
            export apiBaseUrl=//${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_API_PORT }}
            export rAthenaPath=./node_modules/rathena
            export log=verbose

            killall node || echo "Server not running, no need to kill process"
            nohup yarn api:prod > nohup.out 2> nohup.err < /dev/null &
            nohup yarn app:prod > nohup.out 2> nohup.err < /dev/null &
